# Home
GET http://localhost:3001

###

# Create
POST http://localhost:3001/create

###

# Read
GET http://localhost:3001/notes

###

# Update
PATCH http://localhost:3001/update

###

# Delete
DELETE http://localhost:3001/delete


