# Home
GET http://localhost:5000

###

# Authentication
POST http://localhost:5000/api/auth

###

# Create
POST http://localhost:5000/api/create

###

# Read
GET http://localhost:5000/api/notes

###

# Update
PATCH http://localhost:5000/api/update

###

# Delete
DELETE http://localhost:5000/api/delete


